services:

  ftpcalamar:

    build:
      context: .
      dockerfile: Dockerfile

    image: christense/ftpcalamar:latest

    container_name: ftpcalamar

    hostname: ftpcalamar

    restart: unless-stopped

    ports:
      - "80:80"
      - "443:443"
      - "21:21"
      - "2222:22"
      - "30000-30100:30000-30100"

    volumes:
      - ./data/storage:/data/storage
      - ./data/logs:/data/logs
      - ./data/certs:/data/certs
      - ./data/config:/data/config

    environment:
      TZ: America/Argentina/Buenos_Aires
