[supervisord]
nodaemon=true
user=root

[program:sshd]
command=/usr/sbin/sshd -D
autorestart=true
priority=5

[program:vsftpd]
command=/usr/sbin/vsftpd /etc/vsftpd.conf
autorestart=true
priority=10

[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
autorestart=true
priority=15

[program:node]
directory=/app/backend
command=node server.js
autorestart=true
priority=20
